api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api import views

app_name = "api"

router = DefaultRouter()

router.register('technologies', views.TechnologyViewSet , basename='techs')

urlpatterns = [
    path("jobs/", views.ListJobsAPIView.as_view(), name="list_jobs"),
    path("jobs/<int:pk>/", views.ListSingleJobAPIView.as_view(), name="list_specific_job"),
    path("scraper/", views.CreateScraperJobView.as_view(), name="setup_scraper_job"),

    path("job_progress/", views.WatchScraperJobView.as_view(), name="job_progress"),
    
]

urlpatterns += router.urls

console/urls.py
from django.urls import path

from console import views

app_name = "console"

urlpatterns = [
    path("", views.index, name="index"),
    path("scrape/", views.scrape, name="scrape"),
    
]

src/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include


from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from rest_framework import permissions

# From DRF Swagger cli
# https://github.com/axnsan12/drf-yasg/
schema_view = get_schema_view(
    openapi.Info(
        title="Beekin Assignement",
        default_version="v1",
        description="Beekin API Documentation with DRF",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@email.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('', include('console.urls')),
    path('api/v1/', include('api.urls')),
    path('admin/', admin.site.urls),

    # Documentation
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
]

api/models.py
from django.db import models


class Technology(models.Model):
	name = models.CharField('Name', unique=True, max_length=100, blank=True)

	def __str__(self):
		return self.name

class Job(models.Model):
	"""
	Job Model
	"""
	class Meta:
		ordering = ['-pk']

	created_at = models.DateTimeField(auto_now_add=True)

	indeed_link = models.CharField('Indeed link', unique=True, max_length=200, blank=True)
	title = models.CharField('Title', max_length=100, blank=True)
	location = models.CharField('Location', max_length=60, blank=True)
	description = models.TextField('Job Description', blank=True)

	tech = models.ManyToManyField(Technology, related_name='technology')

	experience_required = models.CharField('Experience', max_length=255, blank=True)

	company_name = models.CharField('Company', max_length=100, blank=True)

	posted_date = models.DateField('Post Date', null=True, blank=True)
	responsabilities = models.TextField('Responsabilities',  blank=True)

	def __str__(self):
		return self.title

console/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework.permissions import AllowAny

from rest_framework.views import APIView
from rest_framework import viewsets

from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView
)

from api.pagination import JobLimitOffsetPagination
from api.models import Job, Technology
from api.serializers import (
    JobListSerializer,
    TechnologySerializer
)
from api.filters import (
		JobFilter
	)

from rest_framework import filters
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend

from django.http.response import JsonResponse

from src.tasks import scrapeIndeed
from celery.result import AsyncResult

class ListJobsAPIView(ListAPIView):
    """
    get:
        Returns a list of all existing posts
    """

    queryset = Job.objects.all()
    serializer_class = JobListSerializer
    permission_classes = (AllowAny, )
    pagination_class = JobLimitOffsetPagination
    filter_backends = [filters.SearchFilter, DjangoFilterBackend]
    filter_class = JobFilter
    search_fields = ('title', )
    lookup_field = "id"
    ordering_fields = ('id', 'title')

class ListSingleJobAPIView(RetrieveAPIView):
    """
    get:
        Returns a specific job by id if exists
    """

    queryset = Job.objects.all()
    serializer_class = JobListSerializer
    permission_classes = (AllowAny, )


class TechnologyViewSet(viewsets.ModelViewSet):
    """
    A viewset for Technology instances.
    """
    queryset = Technology.objects.all()
    serializer_class = TechnologySerializer
    permission_classes = (AllowAny, )
    

class CreateScraperJobView(APIView):
    """
    post:
        Creates a new scraper job.
    """

    permission_classes = (AllowAny, )

    def post(self, request, *args, **kwargs):
        options = request.data
        if "query" not in options:
            return Response({"message" : "query is required"}, status=400)
        if "language" not in options:
            return Response({"message" : "language is required"}, status=400)
        else:
            if options["language"] not in ['en', 'fr', 'uk', 'de']:
                return Response({"message" : "specify a valid choise of language ['en', 'fr', 'uk', 'de']"}, status=400)


        celery_task = scrapeIndeed.delay(options)
        return Response({"task_id" : celery_task.id }, status=200)

class WatchScraperJobView(APIView):
    """
    post:
        Watch progress of scraper job based on job ID.
    """

    permission_classes = (AllowAny, )

    def post(self, request, *args, **kwargs):
        options = request.data
        if "job_id" not in options:
            return Response({"message" : "job_id is required"}, status=400)

        try:
            job = AsyncResult(options["job_id"])
            data = job.result or job.state
            return Response({"result" : data }, status=200)
        except:
            return Response({"message" : "JOB ID not found" }, status=200)

console/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from src.tasks import scrapeIndeed

def index(request):
    """
    Defining nested page for scrapping indeed
    """
    return render(
                request,
                "console/index.html",
                {},
            )

def scrape(request):
	"""
	Run scraping for selected preferences
	"""
	if request.method == "POST":
		q = request.POST.get("query")
		if not q:
			messages.error(request, 'Query is required')
			return redirect('console:index')
		options = {
			"query" : request.POST.get("query"),
			"language" : request.POST.get("language"),
			"location" : request.POST.get("location"),
			"radius" : request.POST.get("radius"),
			"limit" : request.POST.get("limit")
		}
		# Running Job in Redis Broker
		scrapeIndeed.delay(options)

		messages.success(request, 'Request successfully added to queue and would be processed shortly')
		return redirect('console:index')


		
		

console/templates/console/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Beekin Indeed Scraper API</title>
</head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<body>

	{% block content %}
	{% endblock %}

</body>
</html>

console/templates/console/index.html
{% extends "console/base.html" %}

{% block content %}

<style type="text/css">
	.formbox {
		margin-top:10%;
	}
</style>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissable {% if message.tags == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}">
            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
            {{ message|linebreaks }}
        </div>
    {% endfor %}
{% endif %}

<div class="container h-100 formbox">
    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto vertical-center">
            <div class="card h-100 border-primary justify-content-center d-flex align-items-center border-0">
                <div>
                   <div class="row">
						<form method="POST" action="{% url 'console:scrape' %}">{% csrf_token %}
						  <div class="mb-3">
						    <label for="query" class="form-label">Query</label>
						    <input type="text" class="form-control" id="query" name="query" aria-describedby="query">
						    <div id="queryHelp" class="form-text">Query to look for (node, python, express ...).</div>
						  </div>
						  <div class="mb-3">
						    <label for="language" class="form-label">Language</label>
							<select name="language" class="form-control" id="language">
							  <option value="fr">France</option>
							  <option value="en">US</option>
							  <option value="uk">UK</option>
							  <option value="de">Germany</option>
							</select>
						    <div id="languageHelp" class="form-text">Language or country to look for</div>
						  </div>
						  <div class="mb-3">
						    <label for="location" class="form-label">Location</label>
						    <input type="text" class="form-control" name="location" id="location" aria-describedby="location">
						    <div id="locationHelp" class="form-text">location to look for (Paris, London, Nevada ...)</div>
						  </div>
						  <div class="mb-3">
						    <label for="radius" class="form-label">Radius</label>
						    <input type="number" class="form-control" name="radius" id="radius" aria-describedby="radius">
						    <div id="radiusHelp" class="form-text">Radius of search based on location</div>
						  </div>
						  <div class="mb-3">
						    <label for="limit" class="form-label">Nbr of result</label>
						    <input type="number" class="form-control" name="limit" id="limit" aria-describedby="limit">
						    <div id="limitHelp" class="form-text">Number of queries.</div>
						  </div>
						  <button type="submit" class="btn btn-primary pull-right">Scrape</button>
						</form>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}